# Generated by Django 5.2.15 on 2026-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_aboutpage_body_alter_contactpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='intro_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='intro_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='title_ar',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
