# Generated by Django 5.2.15 on 2026-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewWebContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HIG New Website Content', max_length=120)),
                ('hero_text_ar', models.TextField(blank=True)),
                ('hero_text_en', models.TextField(blank=True)),
                ('who_title_ar', models.CharField(blank=True, max_length=220)),
                ('who_title_en', models.CharField(blank=True, max_length=220)),
                ('who_text_ar', models.TextField(blank=True)),
                ('who_text_en', models.TextField(blank=True)),
                ('value_1_title_ar', models.CharField(blank=True, max_length=120)),
                ('value_1_title_en', models.CharField(blank=True, max_length=120)),
                ('value_1_text_ar', models.TextField(blank=True)),
                ('value_1_text_en', models.TextField(blank=True)),
                ('value_2_title_ar', models.CharField(blank=True, max_length=120)),
                ('value_2_title_en', models.CharField(blank=True, max_length=120)),
                ('value_2_text_ar', models.TextField(blank=True)),
                ('value_2_text_en', models.TextField(blank=True)),
                ('value_3_title_ar', models.CharField(blank=True, max_length=120)),
                ('value_3_title_en', models.CharField(blank=True, max_length=120)),
                ('value_3_text_ar', models.TextField(blank=True)),
                ('value_3_text_en', models.TextField(blank=True)),
                ('value_4_title_ar', models.CharField(blank=True, max_length=120)),
                ('value_4_title_en', models.CharField(blank=True, max_length=120)),
                ('value_4_text_ar', models.TextField(blank=True)),
                ('value_4_text_en', models.TextField(blank=True)),
                ('barah_tagline_ar', models.CharField(blank=True, max_length=160)),
                ('barah_tagline_en', models.CharField(blank=True, max_length=160)),
                ('barah_text_ar', models.TextField(blank=True)),
                ('barah_text_en', models.TextField(blank=True)),
                ('caza_text_ar', models.TextField(blank=True)),
                ('caza_text_en', models.TextField(blank=True)),
                ('centro_text_ar', models.TextField(blank=True)),
                ('centro_text_en', models.TextField(blank=True)),
                ('parco_text_ar', models.TextField(blank=True)),
                ('parco_text_en', models.TextField(blank=True)),
                ('featured_title_ar', models.CharField(blank=True, max_length=220)),
                ('featured_title_en', models.CharField(blank=True, max_length=220)),
                ('team_title_ar', models.CharField(blank=True, max_length=180)),
                ('team_title_en', models.CharField(blank=True, max_length=180)),
                ('team_text_ar', models.TextField(blank=True)),
                ('team_text_en', models.TextField(blank=True)),
                ('insights_title_ar', models.CharField(blank=True, max_length=180)),
                ('insights_title_en', models.CharField(blank=True, max_length=180)),
                ('insight_1_ar', models.CharField(blank=True, max_length=220)),
                ('insight_1_en', models.CharField(blank=True, max_length=220)),
                ('insight_2_ar', models.CharField(blank=True, max_length=220)),
                ('insight_2_en', models.CharField(blank=True, max_length=220)),
                ('insight_3_ar', models.CharField(blank=True, max_length=220)),
                ('insight_3_en', models.CharField(blank=True, max_length=220)),
                ('contact_title_ar', models.CharField(blank=True, max_length=180)),
                ('contact_title_en', models.CharField(blank=True, max_length=180)),
                ('contact_text_ar', models.TextField(blank=True)),
                ('contact_text_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'New Website Content',
                'verbose_name_plural': 'New Website Content',
            },
        ),
    ]
