# Generated by Django 5.2.15 on 2026-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwebcontent',
            name='arabic_title_line_height',
            field=models.DecimalField(decimal_places=2, default=1.34, max_digits=3),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='body_font_size',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='body_line_height',
            field=models.DecimalField(decimal_places=2, default=1.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='card_radius',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='content_max_width',
            field=models.PositiveSmallIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='dark_color',
            field=models.CharField(default='#05070a', max_length=20),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='footer_text_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='footer_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='form_opacity',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='header_height',
            field=models.PositiveSmallIntegerField(default=92),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hero_min_height',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hero_poster',
            field=models.ImageField(blank=True, upload_to='newweb/images/'),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hero_title_ar',
            field=models.CharField(blank=True, default='WE KNOW THE ROUTE.', max_length=180),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hero_title_en',
            field=models.CharField(blank=True, default='WE KNOW THE ROUTE.', max_length=180),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hero_title_size',
            field=models.PositiveSmallIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hero_video',
            field=models.FileField(blank=True, upload_to='newweb/videos/'),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='hotline',
            field=models.CharField(default='17556', max_length=30),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='light_color',
            field=models.CharField(default='#f4f8fd', max_length=20),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='logo_width',
            field=models.PositiveSmallIntegerField(default=112),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='navigation_font_size',
            field=models.PositiveSmallIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='primary_color',
            field=models.CharField(default='#1279d7', max_length=20),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='project_title_size',
            field=models.PositiveSmallIntegerField(default=96),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='section_spacing',
            field=models.PositiveSmallIntegerField(default=112),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='section_title_size',
            field=models.PositiveSmallIntegerField(default=88),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_board',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_featured_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_hero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_insights',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_project_lanes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_projects_grid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='show_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='whatsapp_number',
            field=models.CharField(default='201144815252', max_length=30),
        ),
        migrations.AddField(
            model_name='newwebcontent',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
