# Generated by Django 5.2.15 on 2026-07-03 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('project', models.CharField(blank=True, max_length=160)),
                ('unit_type', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('page_url', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('fbp', models.CharField(blank=True, max_length=220)),
                ('fbc', models.CharField(blank=True, max_length=220)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='new', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('google_sheet_synced', models.BooleanField(default=False)),
                ('google_sheet_status', models.CharField(default='pending', max_length=40)),
                ('google_sheet_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tracking.visitorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
