# Generated by Django 5.2.15 on 2026-07-03 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('session_key', models.CharField(default=uuid.uuid4, max_length=80, unique=True)),
                ('first_landing_page', models.URLField(blank=True)),
                ('last_page_url', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('device_browser', models.CharField(blank=True, max_length=220)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_started', 'Session started'), ('page_view', 'Page view'), ('project_view', 'Project view'), ('map_interaction', 'Map interaction'), ('scroll_depth', 'Scroll depth'), ('cta_click', 'CTA click'), ('lead_form_start', 'Lead form start'), ('lead_submit', 'Lead submit')], max_length=40)),
                ('page_url', models.URLField(blank=True)),
                ('project_name', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracking.visitorsession')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
